remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

#Can you predict power outage duration?
### Dylan Babitch
### dbabitch@umich.edu